# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44adc44628a5e4e20548ca0569754cdc7d7a1da698411ca5efe108ece348ff5a2675eedaacca86d6716f05e773b97f1b0ed080c54b8359bf229cf2e95efe7e30

test:
  secret_key_base: 3a47d447eefc190cfca9a7d3e866d852a8264af1b1174867fbbe27174bb2970e6e2a36df5f0e0f6155cb0457e9c0ab57585aa14f96d4073512886890087224a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
